name: Publish Website

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any other dependencies your script needs here

      - name: Run HTML Loader
        run: python html_loader.py  # Replace with your script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Directory of the HTML file
